CC = gcc
CFLAGS = -Wall -Werror

all : mergesort simpleCSVSorter

mergesort : mergesort.c
	$(CC) -c $(CFLAGS) mergesort.c

simpleCSVSorter : simpleCSVSorter.c
	$(CC) $(CFLAGS) simpleCSVSorter.c mergesort.o -o simpleCSVSorter

clean : 
	rm -f simpleCSVSorter mergesort.o